### ISSUE TITLE
make "toggle comments" comment out each line instead of block?

### ISSUE THREAD

**Issue by nrser** [hjson/atom-hjson#2]
hey, is there any way to make "toggle comments" (Cmd+/ in OSX) use line-by-line comments like it does in most grammars? it doest work if the contents have `*/` in them:

``` js
// before Cmd+/
{
  file: "/imports/ui/lib/container/**/*"
  level: trace
}

// after Cmd+/ totally broken:
/*{
  file: "/imports/ui/lib/container/**/*"
  level: trace
}*/
```

**Comment by dannyfritz** [comment]
I'll try to get to this in the next couple days. I understand the problem and agree with the solution.

**Comment by nrser** [comment]
thanks dude. i did a google search or two and skimmed the source but it wasn't obvious to me how to control that feature and i sadly don't have time to go more in depth right now. i work around it with multi-line editing but i think it's def something that should be changed.

**Comment by dannyfritz** [comment]
i asked in the atom slack channel and got no reply. i should probably ask
again.

**Comment by dannyfritz** [comment]
`0.5.0` published with this feature.

**Comment by nrser** [comment]
Awesome!
