### ISSUE TITLE
Comments highlight incorrectly

### ISSUE THREAD

**Issue by Yarn** [hjson/atom-hjson#3]
![untitled](https://cloud.githubusercontent.com/assets/908816/20905855/6d656b38-bafa-11e6-940b-fb0e38d78e76.png)

```
> echo "url: http://google.com" | hjson
{
  url: http://google.com
}

```

**Comment by dannyfritz** [comment]
Indeed. Both of my open issues revolve around comments right now. Hrmmm..

**Comment by Yarn** [comment]
![untitled](https://cloud.githubusercontent.com/assets/908816/20912358/9a3d76ea-bb23-11e6-99c5-052a18a217bb.png)

hmm
