### ISSUE TITLE
Wasn't showing up in atom Preferences

### ISSUE THREAD

**Issue by qm3ster** [hjson/atom-hjson#4]
Update: I was a fool.

**Comment by dannyfritz** [comment]
I have no issues with installing `language-hjson` with a fresh install of Atom through the settings interface.

**Comment by qm3ster** [comment]
I am the quintessential atom user who after two months away from the editor and almost a year since installing an atom package went to the Packages tab instead of Install. Please have mercy.

**Comment by dannyfritz** [comment]
Mercy granted. :+1:
