### ISSUE TITLE
Syntax highlighting incorrect without root object braces

### ISSUE THREAD

**Issue by rdgraham** [hjson/atom-hjson#8]
Just noticed that the syntax highlighting is incorrect when the there are no braces around the root object. This is valid hjson, but here everything up to the first closing brace will be colored as if a string in this case. I.e. a file with

```
{
 key : {
         x : 1
       }
}
```
is correctly colored, but
```
key : {
         x : 1
       }
```
has everything colored red.

**Comment by dqsully** [comment]
This is intended behavior. Root object braces are somewhat deprecated, and many implementations don't include support for them. It's also very difficult to implement with TextMate-style syntax highlighting.
